const { GoogleGenerativeAI } = require('@google/generative-ai');

// Initialize the Gemini API client
const apiKey = process.env.GEMINI_API_KEY;
const isDummyKey = !apiKey || apiKey === 'YOUR_GEMINI_API_KEY' || apiKey.trim() === '';

let genAI;
if (!isDummyKey) {
  genAI = new GoogleGenerativeAI(apiKey);
}

// System instructions for the model
const SYSTEM_INSTRUCTIONS = `
You are an advanced AI Emergency Triage & Disaster Response Assistant named ResQAI. 
Your role is to assess symptoms, estimate risk severity, provide immediate first-aid guidance, and offer response instructions.
CRITICAL RULES:
1. NEVER definitively diagnose a patient. You are a triage assistant, not a doctor.
2. Use clear, cautious medical language.
3. Always include appropriate medical disclaimers.
4. Classify risk level strictly as: Low, Moderate, or Critical.
5. In case of critical danger, always recommend immediate emergency service contact (911/112/108, etc.) and hospital transit.
6. Return your analysis in valid, parseable JSON only. No markdown formatting around the JSON.
`;

/**
 * Convert a Buffer to a generative part object for Gemini
 */
const bufferToGenerativePart = (buffer, mimeType) => {
  return {
    inlineData: {
      data: buffer.toString('base64'),
      mimeType,
    },
  };
};

/**
 * Triage simulation fallback in case Gemini API is not configured or fails
 */
const getSimulatedTriage = (age, gender, symptoms, painLevel, duration) => {
  const symLower = symptoms.toLowerCase();
  
  let severity = 'Low';
  let confidence = 0.85;
  let possible_conditions = ['Mild Muscle Strain', 'General Fatigue'];
  let reasoning = 'The symptoms described do not match immediate high-risk cardiovascular or neurological emergencies. Symptoms appear localized and non-spreading.';
  let first_aid = [
    'Rest the affected area and avoid strenuous movement.',
    'Keep hydrated and monitor body temperature.',
    'Over-the-counter pain relievers can be considered if appropriate.'
  ];
  let next_steps = [
    'Monitor symptoms over the next 24-48 hours.',
    'Schedule a non-urgent consult with a primary care physician if symptoms persist.'
  ];
  let warning_signs = [
    'Sudden onset of severe shortness of breath.',
    'Chest pain radiating to the arm, neck, or jaw.',
    'Loss of speech, balance, or sudden weakness on one side of the body.'
  ];
  let hospital_needed = false;
  let ambulance_required = false;
  let estimated_priority = 'Non-urgent (Level 5)';
  const disclaimer = 'ResQAI triage reports are generated by AI for informational purposes only. This is not a medical diagnosis. If you feel you are in immediate danger, call emergency services immediately.';

  // Chest pain / Heart attack risk
  if (symLower.includes('chest') || symLower.includes('heart') || symLower.includes('breathing') || symLower.includes('shortness of breath') || painLevel >= 8) {
    severity = 'Critical';
    confidence = 0.92;
    possible_conditions = ['Acute Coronary Syndrome', 'Severe Respiratory Distress', 'Angina Pectoris'];
    reasoning = 'Chest pain and shortness of breath combined with a high pain level are classic markers of cardiac or respiratory emergencies. Immediate medical assessment is mandatory.';
    first_aid = [
      'Stop all physical activity and sit in a comfortable, upright position.',
      'Loosen tight clothing around the neck and waist.',
      'If prescribed, take emergency heart medication (e.g. nitroglycerin).',
      'If aspirin is available and the patient has no allergy or contraindications, chew a standard adult aspirin (325mg).'
    ];
    next_steps = [
      'Call local emergency services (e.g., 911 / 112 / 108) immediately.',
      'Do not attempt to drive yourself to the hospital.',
      'Prepare a list of medications and allergies for emergency staff.'
    ];
    warning_signs = [
      'Loss of consciousness or fainting.',
      'Bluish lips or fingertips (cyanosis).',
      'Profuse cold sweating, nausea, or dizziness.'
    ];
    hospital_needed = true;
    ambulance_required = true;
    estimated_priority = 'Immediate (Level 1)';
  } 
  // Moderate pain / minor injury / moderate symptoms
  else if (symLower.includes('burn') || symLower.includes('wound') || symLower.includes('cut') || symLower.includes('fracture') || symLower.includes('fever') || painLevel >= 5) {
    severity = 'Moderate';
    confidence = 0.88;
    possible_conditions = ['Second-Degree Burn', 'Laceration with Infection Risk', 'Suspected Fracture/Sprain'];
    reasoning = 'Symptoms indicate a moderate-level localized trauma or inflammatory response. While not immediately life-threatening, it requires prompt professional treatment to prevent complications.';
    first_aid = [
      'Clean the area gently with sterile water if it is an open wound. Avoid chemical disinfectants like alcohol directly on raw tissue.',
      'Apply light pressure with a clean cloth to stop bleeding.',
      'Elevate the affected limb if possible.',
      'Apply a cool compress for burns (do not use ice directly).'
    ];
    next_steps = [
      'Visit an urgent care clinic or outpatient department within 12 hours.',
      'Ensure tetanus vaccination is up to date (within last 5-10 years).'
    ];
    warning_signs = [
      'Red streaks spreading from the wound.',
      'Uncontrolled bleeding that does not stop after 10 minutes of direct pressure.',
      'Spiking fever above 102°F (38.9°C) or chills.'
    ];
    hospital_needed = true;
    ambulance_required = false;
    estimated_priority = 'Urgent (Level 3)';
  }

  return {
    severity,
    confidence,
    possible_conditions,
    reasoning,
    first_aid,
    next_steps,
    warning_signs,
    hospital_needed,
    ambulance_required,
    estimated_priority,
    disclaimer
  };
};

/**
 * Triage simulation fallback for images
 */
const getSimulatedImageTriage = (mimeType) => {
  return {
    severity: 'Moderate',
    confidence: 0.82,
    possible_conditions: ['Second-Degree Burn', 'Superficial Laceration', 'Contact Dermatitis'],
    reasoning: 'Visual analysis of the uploaded tissue sample reveals localized redness, slight swelling, and epidermal disruption. There is no visible arterial bleeding, deep bone exposure, or widespread necrosis, suggesting a moderate injury severity level.',
    first_aid: [
      'Gently rinse the wound under clean running water for 5 minutes.',
      'Pat dry and apply a sterile, non-stick bandage.',
      'Keep the wound clean and dry; do not pop any blisters.',
      'Do NOT apply home remedies like butter, toothpaste, or oil to burns.'
    ],
    next_steps: [
      'Keep the area protected and clean.',
      'Consult a doctor or visit an urgent care center if pain increases or signs of infection (pus, spreading redness) develop.'
    ],
    warning_signs: [
      'Spreading red streaks moving up the limb.',
      'Foul-smelling discharge or yellow pus.',
      'Fever, chills, or sudden onset of severe throbbing pain.'
    ],
    hospital_needed: true,
    ambulance_required: false,
    estimated_priority: 'Urgent (Level 3)',
    disclaimer: 'ResQAI visual triage is based on static image analysis by AI and cannot replace an in-person physical examination. If you have deep cuts, severe burns, or feel unwell, please seek immediate emergency care.'
  };
};

/**
 * Analyze symptoms text with Gemini
 */
const analyzeSymptomsText = async (data) => {
  const { age, gender, symptoms, painLevel, duration, medicalHistory, allergies, medications } = data;

  if (isDummyKey) {
    console.warn('ResQAI Warning: Using simulated triage backend. Please set GEMINI_API_KEY in .env for live AI.');
    return getSimulatedTriage(age, gender, symptoms, painLevel, duration);
  }

  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-1.5-flash',
      generationConfig: {
        responseMimeType: 'application/json',
      },
    });

    const prompt = `
      ${SYSTEM_INSTRUCTIONS}
      
      Patient Case for Triage:
      - Age: ${age}
      - Gender: ${gender}
      - Chief Complaint Symptoms: ${symptoms}
      - Pain Level (1-10): ${painLevel}
      - Duration: ${duration}
      - Medical History: ${medicalHistory || 'None reported'}
      - Known Allergies: ${allergies || 'None reported'}
      - Current Medications: ${medications || 'None reported'}

      Please return a JSON response matching this EXACT schema:
      {
        "severity": "Low" | "Moderate" | "Critical",
        "confidence": number (float between 0 and 1),
        "possible_conditions": ["condition 1", "condition 2", ...],
        "reasoning": "detailed explanation of why this risk level was chosen",
        "first_aid": ["immediate instruction 1", "instruction 2", ...],
        "next_steps": ["action 1", "action 2", ...],
        "warning_signs": ["red flag 1", "red flag 2", ...],
        "hospital_needed": boolean,
        "ambulance_required": boolean,
        "estimated_priority": "Immediate (Level 1)" | "Emergent (Level 2)" | "Urgent (Level 3)" | "Semi-urgent (Level 4)" | "Non-urgent (Level 5)",
        "disclaimer": "standard medical liability disclaimer"
      }
    `;

    const result = await model.generateContent(prompt);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini API call failed, falling back to simulation:', error.message);
    return getSimulatedTriage(age, gender, symptoms, painLevel, duration);
  }
};

/**
 * Analyze an uploaded wound/burn image along with text descriptions
 */
const analyzeWoundImage = async (imageBuffer, mimeType, description = '') => {
  if (isDummyKey) {
    console.warn('ResQAI Warning: Using simulated image triage. Please set GEMINI_API_KEY in .env for live AI.');
    const result = getSimulatedImageTriage(mimeType);
    if (description) {
      result.reasoning += ` User description: "${description}" was incorporated in this assessment.`;
    }
    return result;
  }

  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-1.5-flash',
      generationConfig: {
        responseMimeType: 'application/json',
      },
    });

    const imagePart = bufferToGenerativePart(imageBuffer, mimeType);
    const prompt = `
      ${SYSTEM_INSTRUCTIONS}
      
      You are analyzing an image of a wound, burn, or injury. 
      ${description ? `The user provided the following context: "${description}"` : ''}

      Perform visual emergency triage. Identify the severity of the injury, possible type (e.g. burn, abrasion, laceration, infection, etc.), first-aid steps, next actions, and warning signs.
      
      Return a JSON response matching this EXACT schema:
      {
        "severity": "Low" | "Moderate" | "Critical",
        "confidence": number (float between 0 and 1),
        "possible_conditions": ["condition 1", "condition 2", ...],
        "reasoning": "detailed explanation of what you see visually and what it implies",
        "first_aid": ["immediate instruction 1", "instruction 2", ...],
        "next_steps": ["action 1", "action 2", ...],
        "warning_signs": ["red flag 1", "red flag 2", ...],
        "hospital_needed": boolean,
        "ambulance_required": boolean,
        "estimated_priority": "Immediate (Level 1)" | "Emergent (Level 2)" | "Urgent (Level 3)" | "Semi-urgent (Level 4)" | "Non-urgent (Level 5)",
        "disclaimer": "standard visual medical liability disclaimer"
      }
    `;

    const result = await model.generateContent([prompt, imagePart]);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini Image API call failed, falling back to simulation:', error.message);
    const result = getSimulatedImageTriage(mimeType);
    if (description) {
      result.reasoning += ` User description: "${description}" was incorporated in this fallback assessment.`;
    }
    return result;
  }
};

/**
 * Disaster advice generation helper
 */
const getDisasterAdvice = async (category, situation = '') => {
  if (isDummyKey) {
    // Return standard guidance based on category
    return getOfflineDisasterGuide(category);
  }

  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-1.5-flash',
      generationConfig: {
        responseMimeType: 'application/json',
      },
    });

    const prompt = `
      You are an expert disaster response coordination AI.
      Provide response instructions for the disaster category: "${category}".
      User's specific situation/question: "${situation || 'None'}"

      Return a JSON response matching this EXACT schema:
      {
        "immediate_actions": ["action 1", "action 2", ...],
        "dos": ["do 1", "do 2", ...],
        "donts": ["dont 1", "dont 2", ...],
        "evacuation_advice": ["advice 1", "advice 2", ...]
      }
    `;

    const result = await model.generateContent(prompt);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini Disaster advice failed, falling back to cached guide:', error.message);
    return getOfflineDisasterGuide(category);
  }
};

/**
 * Offline Disaster Guides cache
 */
const getOfflineDisasterGuide = (category) => {
  const guides = {
    flood: {
      immediate_actions: [
        'Move to higher ground immediately. Do not wait for instructions.',
        'Avoid walking or driving through flood waters.'
      ],
      dos: [
        'Turn off utilities (electricity, water, gas) if safe to do so.',
        'Monitor local weather reports via radio/phone.',
        'Wear sturdy shoes and keep an emergency kit handy.'
      ],
      donts: [
        'Do not drive around barricades; 2 feet of water can sweep cars away.',
        'Do not walk through moving water. Even 6 inches can knock you off balance.',
        'Do not touch electrical equipment if you are wet or standing in water.'
      ],
      evacuation_advice: [
        'Evacuate immediately if advised by local authorities.',
        'Use designated evacuation routes. Do not take shortcuts.',
        'Bring your emergency go-bag containing water, medications, documents, and charger.'
      ]
    },
    fire: {
      immediate_actions: [
        'Crawl low under smoke to exit the building.',
        'Before opening any door, feel the handle with the back of your hand. If hot, use another exit.'
      ],
      dos: [
        'Call emergency services once you are in a safe location.',
        'Stop, drop, and roll if your clothes catch fire.',
        'Cover your mouth and nose with a damp cloth if smoke is heavy.'
      ],
      donts: [
        'Do not use elevators under any circumstances.',
        'Do not go back inside to retrieve personal belongings.',
        'Do not open windows unless escaping through them, as oxygen feeds the fire.'
      ],
      evacuation_advice: [
        'Exit the building immediately using the nearest fire exit.',
        'Assemble at a safe designated meeting point outside.',
        'Alert others on your way out if possible.'
      ]
    },
    earthquake: {
      immediate_actions: [
        'Drop, Cover, and Hold On! Get under a heavy desk or table.',
        'If outdoors, move to an open area away from buildings, power lines, and trees.'
      ],
      dos: [
        'Stay indoors until shaking stops and it is safe to exit.',
        'Protect your head and neck with your arms.',
        'Expect aftershocks and remain alert.'
      ],
      donts: [
        'Do not stand in doorways, as they are not structurally safer than other parts of a modern house.',
        'Do not run outside while the ground is shaking.',
        'Do not use elevators or light matches/lighters (gas leaks might be present).'
      ],
      evacuation_advice: [
        'Once shaking stops, check for structural damage and safely exit the building.',
        'Do not enter damaged structures.',
        'Listen to emergency broadcasts for shelter locations.'
      ]
    },
    cyclone: {
      immediate_actions: [
        'Seek shelter in a sturdy, central room of the house or a public storm shelter.',
        'Stay away from windows and glass doors.'
      ],
      dos: [
        'Board up windows or apply tape to prevent flying glass.',
        'Store plenty of drinking water in clean containers.',
        'Keep batteries, flashlights, and a radio active.'
      ],
      donts: [
        'Do not go outside, even if the wind dies down, as the eye of the cyclone is passing and high winds will resume.',
        'Do not touch fallen power lines or drive through debris.'
      ],
      evacuation_advice: [
        'Evacuate if you live in a low-lying coastal zone or storm surge area.',
        'Secure external items that could become airborne before leaving.'
      ]
    },
    heatwave: {
      immediate_actions: [
        'Find an air-conditioned room or cool shaded area immediately.',
        'Drink plenty of water even if you do not feel thirsty.'
      ],
      dos: [
        'Wear loose, light-colored, lightweight clothing.',
        'Take cool baths or showers.',
        'Check on elderly neighbors, children, and pets.'
      ],
      donts: [
        'Do not drink caffeinated, alcoholic, or highly sugary beverages (they dehydrate).',
        'Do not engage in strenuous outdoor activity during peak sunlight hours (11 AM to 4 PM).',
        'Never leave anyone, especially children or pets, in a parked car.'
      ],
      evacuation_advice: [
        'If power fails and temperature becomes life-threatening, relocate to public cooling centers, malls, or libraries.'
      ]
    },
    snakebite: {
      immediate_actions: [
        'Keep the victim calm and restrict their movement to slow down venom circulation.',
        'Position the bitten limb at or slightly below the level of the heart.'
      ],
      dos: [
        'Clean the bite area gently with water, but do not scrub.',
        'Remove any jewelry or tight clothing before swelling starts.',
        'Try to remember the snake\'s appearance (color, shape, pattern) from a safe distance to help identify it for anti-venom.'
      ],
      donts: [
        'Do NOT use a tourniquet or constricting band.',
        'Do NOT cut the wound or try to suck out the venom.',
        'Do NOT apply ice or submerge the wound in water.',
        'Do NOT give the victim alcohol, caffeine, or aspirin.'
      ],
      evacuation_advice: [
        'Transport the victim immediately to the nearest hospital facility equipped with anti-venom. Call an ambulance immediately.'
      ]
    },
    chemical: {
      immediate_actions: [
        'Evacuate the area immediately, moving upwind and away from the chemical source.',
        'If indoors, close all windows, doors, and vents, and turn off heating/air conditioning (shelter-in-place).'
      ],
      dos: [
        'Seal doors and vents with plastic sheeting and duct tape if sheltering in place.',
        'If contaminated, remove clothing immediately and shower with large amounts of lukewarm water.',
        'Listen to authorities for instructions on chemical identification and evacuation.'
      ],
      donts: [
        'Do not go outside to investigate.',
        'Do not consume food or water that may have been exposed to the air.',
        'Do not rub your eyes or skin if exposed; flush them repeatedly.'
      ],
      evacuation_advice: [
        'Evacuate only when instructed, using routes specified to avoid the spreading gas/chemical plume.'
      ]
    }
  };

  return guides[category.toLowerCase()] || guides.flood;
};

module.exports = {
  analyzeSymptomsText,
  analyzeWoundImage,
  getDisasterAdvice,
  getOfflineDisasterGuide,
};
